; Original Author  : Aditya Shakya
; Mail    : adi1090x@gmail.com
; Modified by : Daniel Heras
; Mail    : dani.heras@hotmail.com

[color]
background = #FF121212
foreground = #ced4da
foreground-alt = #ced4da
primary = #2a6f97
primary-dark = #415a77
primary-light = #61a5c2
red = #bc4749
green = #4c956c
yellow = #e9c46a
complementary = #415a77
