font_family			Source Code Pro
font_size 			12
bold_font        	auto
italic_font      	auto
bold_italic_font 	auto

background_opacity 0.95
color0 	#313539
color1 	#ba181b
color2 	#25a244
color3 	#FDCC00
color4 	#0353a4
color5 	#9d4edd
color6 	#2196f3
color7 	#E0E3E7

color8 	#676f78
color9 	#e5383b
color10 #2dc653
color11 #ffff50
color12 #0466c8
color13 #c77dff
color14 #42a5f5
color15 #FEFFFF

background #030307
foreground #d8dee9

cursor #cccccc
cursor_text_color #111111
cursor_shape block
cursor_blink_interval 0

mouse_hide_wait 3.5
enable_audio_bell no

confirm_os_window_close 0

detect_urls yes
url_prefixes http https file ftp gemini irc gopher mailto news git

input_delay 1

window_margin_width 6 6
