font_family			SauceCodePro NF Medium
font_size 			12
bold_font        	auto
italic_font      	auto
bold_italic_font 	auto

background_opacity 0.93
color0 	#212529
color1 	#c1121f
color2 	#25a244
color3 	#fcf45d
color4 	#0466c8
color5 	#6f2dbd
color6 	#3da5d9
color7 	#E0E3E7
               
color8 	#495057
color9 	#ce4257
color10 #40916c
color11 #ffd166
color12 #0077b6
color13 #815ac0
color14 #61a5c2
color15 #FEFFFF

background #101010
foreground #d8dee9

cursor #cccccc
cursor_text_color #111111
cursor_shape block
cursor_blink_interval 0

mouse_hide_wait 3.5
enable_audio_bell no

confirm_os_window_close 0

detect_urls yes
url_prefixes http https file ftp gemini irc gopher mailto news git

input_delay 1

window_margin_width 6 6
