;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; │░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; main colors
;background = #13151A
;background = #0a0908
;background = #101518
;background = #080705
background = #D9000000
;background = #00000000
foreground = #C4C7C5
sep = #3F5360

white = #FFFFFF
black = #000000
red = #EC7875
pink = #EC407A
purple = #BA68C8
blue = #42A5F5
cyan = #4DD0E1
teal = #00B19F
green = #61C766
lime = #B9C244
yellow = #FDD835
amber = #FBC02D
orange = #E57C46
brown = #AC8476
indigo = #6C77BB
gray = #9E9E9E
blue-gray = #6D8895

;; Mis colores
menu = #0d47a1
ws-activo = #b7094c
ws-ocupado = #1565c0
cpu = #1976d2
ram = #1e88e5
memoria = #2196f3
temperatura = #42a5f5
temperatura-aviso = #a01a58
musica = #b7094c
musica-boton = #b7094c
musica-boton-2 = #b7094c
musica-boton-3 = #b7094c
fecha = #b7094c
bateria = #2196f3
bateria-carga = #80ed99
bateria-llena = #b7094c
volumen = #1e88e5
volumen-2 = #0d47a1
volumen-3 = #2196f3
volumen-4 = #e3f2fd
volumen-mute = #b7094c
brillo = #1976d2
brillo-2 = #0d47a1
brillo-3 = #2196f3
brillo-4 = #e3f2fd
conexion = #1565c0
pmenu = #0d47a1
pmenu-2 = #b7094c

;; Old
#menu = #0d47a1
#ws-activo = #b7094c
#ws-ocupado = #1565c0
#cpu = #1976d2
#ram = #1e88e5
#memoria = #2196f3
#temperatura = #42a5f5
#temperatura-aviso = #a01a58
#musica = #b7094c
#musica-boton = #b7094c
#musica-boton-2 = #b7094c
#musica-boton-3 = #b7094c
#fecha = #b7094c
#bateria = #2196f3
#bateria-carga = #80ed99
#bateria-llena = #b7094c
#volumen = #1e88e5
#volumen-2 = #0d47a1
#volumen-3 = #2196f3
#volumen-4 = #e3f2fd
#volumen-mute = #b7094c
#brillo = #1976d2
#brillo-2 = #0d47a1
#brillo-3 = #2196f3
#brillo-4 = #e3f2fd
#conexion = #1565c0
#pmenu = #0d47a1
#pmenu-2 = #b7094c
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
