;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; │░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; main colors
background = #09090a
;background = #141C21
foreground = #F5F5F5
foreground-alt = #FFFFFF
alpha = #00000000

warn1 = #E9C46A
warn2 = #E76F51
warn3 = #D62828

;; new shades
shade1 = #141C21
shade2 = #263238
shade3 = #37474F
shade4 = #455A64
shade5 = #546E7A
shade6 = #607D8B
shade7 = #78909C
shade8 = #90A4AE
shade9 = #B0BEC5

;; original shades
;shade1 = #141C21
;shade2 = #263238
;shade3 = #37474F
;shade4 = #455A64
;shade5 = #546E7A
;shade6 = #607D8B
;shade7 = #78909C
;shade8 = #90A4AE
;shade9 = #B0BEC5

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
