; Original Author  : Aditya Shakya
; Mail    : adi1090x@gmail.com
; Modified by : Daniel Heras
; Mail    : dani.heras@hotmail.com

[color]
background = #00060606
foreground = #ced4da
foreground-alt = #ced4da
primary = #58809a
red = #bc4749
green = #4c956c
yellow = #0077b6
blue = #58809a
complementary = #415a77
gray = #343a40
dark-gray = #202020
black = #000000
purple = #9984d4
turquoise = #72efdd
